<?php

namespace SchenkeIo\LaravelSheetBase;

use SchenkeIo\LaravelSheetBase\Console\Commands\SheetBaseCheckCommand;
use SchenkeIo\LaravelSheetBase\Console\Commands\SheetBasePumpCommand;
use Spatie\LaravelPackageTools\Commands\InstallCommand;
use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;

class LaravelSheetBaseServiceProvider extends PackageServiceProvider
{
    public function configurePackage(Package $package): void
    {
        //        $this->publishes(
        //            [
        //                __DIR__ . '/../config/sheet-base.php' => config_path('sheet-base.php'),
        //            ],
        //            'laravel-sheet-base-config'
        //        );
        /*
         * More info: https://github.com/spatie/laravel-package-tools
         */

        $package->name('laravel-sheet-base')
            ->hasCommand(SheetBasePumpCommand::class)
            ->hasCommand(SheetBaseCheckCommand::class)
            ->hasConfigFile('sheet-base')
            ->hasInstallCommand(function (InstallCommand $command) {
                $command->publishConfigFile();
            });
    }
    //    public function booting(Package|\Closure $callback)
    //    {
    //        if ($this->app->runningInConsole()) {
    //            $this->commands([
    //                SheetBasePumpCommand::class,
    //                SheetBaseCheckCommand::class
    //            ]);
    //        }
    //        return parent::boot(); // TODO: Change the autogenerated stub
    //    }
}
